package com.workflowx.common.enums;
public enum ActivityType {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_PRIORITY_CHANGED,
    COMMENT_ADDED,
    COMMENT_EDITED,
    COMMENT_DELETED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    SPRINT_CREATED,
    SPRINT_STARTED,
    SPRINT_COMPLETED,
    MEMBER_ADDED,
    MEMBER_REMOVED
}
